// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKaj5hBiLijxpc7MZuDhvUPxDofCkmO34',
    appId: '1:55131395283:web:7464f9764dd2d2b527f026',
    messagingSenderId: '55131395283',
    projectId: 'notification-96949',
    authDomain: 'notification-96949.firebaseapp.com',
    storageBucket: 'notification-96949.firebasestorage.app',
    measurementId: 'G-W0WQR32TCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaLIZwKOIFaJrkbksFP6eBMYlwNsNua3k',
    appId: '1:55131395283:android:208c13b30f69c8b627f026',
    messagingSenderId: '55131395283',
    projectId: 'notification-96949',
    storageBucket: 'notification-96949.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChEFjIaAeeVC_qIgUCQ49bczY-UfeLVKw',
    appId: '1:55131395283:ios:ef2a27f90e8dc0b127f026',
    messagingSenderId: '55131395283',
    projectId: 'notification-96949',
    storageBucket: 'notification-96949.firebasestorage.app',
    iosBundleId: 'com.example.notifcation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChEFjIaAeeVC_qIgUCQ49bczY-UfeLVKw',
    appId: '1:55131395283:ios:ef2a27f90e8dc0b127f026',
    messagingSenderId: '55131395283',
    projectId: 'notification-96949',
    storageBucket: 'notification-96949.firebasestorage.app',
    iosBundleId: 'com.example.notifcation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKaj5hBiLijxpc7MZuDhvUPxDofCkmO34',
    appId: '1:55131395283:web:2dc5a8c9229f025e27f026',
    messagingSenderId: '55131395283',
    projectId: 'notification-96949',
    authDomain: 'notification-96949.firebaseapp.com',
    storageBucket: 'notification-96949.firebasestorage.app',
    measurementId: 'G-8RR5S0CQHE',
  );
}
